version: '3'

services:
  api:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    env_file:
      - /api/.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    

  db:
    build: db  # Properly indented "build" key under the "db" service
    ports:
      - "6379:6379"
    volumes:
      - shorten-url-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  shorten-url-data:
